name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
  - cron: "0 0 * * *"
    branches:
      - 'master'

jobs:
  validation:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '7.4',
            '8.0'
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-version }}
            extensions: mbstring, intl, pdo_mysql

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
            echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: ${{ runner.os }}-composer-

      - name: Check PHP for syntax errors
        run: find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

      - name: Composer install
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: CodeStyle checks
        run: composer cs-check

      - name: Static analysis
        run: composer phpstan

      - name: Codeception tests
        run: composer test
